- name: Add joe user
  user:
    name: joe
    shell: /bin/bash
    groups: sudo
    append: yes
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
      - /var/www
      - /etc/apache2/sites-enabled
  become: true

- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ item }}"
  become: true
  with_items:
      - automysqlbackup
      - fail2ban
      - git
      - php7.0
      - php7.0-curl
      - php7.0-mbstring
      - php7.0-simplexml

- name: Clone git repos
  git:
      repo: "https://github.com/joereynolds/{{ item }}"
      dest: "/var/www/{{ item }}"
  with_items:
      - boganspunkrock
      - util.joereynoldsaudio
      - joereynoldsaudio
      - metronome
  become: true

- name: Copy Apache configurations
  copy:
    src: ./roles/common/files/{{ item }}
    dest: /etc/apache2/sites-enabled/{{ item }}
  with_items:
      - boganspunkrock.conf
      - staging.boganspunkrock.conf
      - metronome.joereynoldsaudio.conf
      - util.joereynoldsaudio.conf
  become: true

- name: Set Postfix option hostname
  debconf: name=postfix question="postfix/mailname" value="{{ansible_fqdn}}" vtype="string"
  become: true

- name: Set Postfix option type as internet site
  debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"
  become: true

- name: Install Postfix
  apt: package={{ item }}
  with_items:
    - postfix
    - mailutils
  become: true
