- name: Add joe user
  user:
    name: joe
    shell: /bin/bash
    groups: sudo
    append: yes
  become: true

- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ item }}"
  become: true
  with_items:
      - fail2ban
      - git
      - php7.0
      - php7.0-curl
      - php7.0-mbstring
      - php7.0-simplexml
