- name: Add joe user
  user:
    name: joe
    shell: /bin/bash
    groups: sudo, www-data
    append: yes
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
      - /var/www
      - /var/www/minio
  become: true

- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ item }}"
  become: true
  with_items:
      - automysqlbackup
      - docker-compose
      - fail2ban
      - pwgen

- name: Clone git repos
  git:
      repo: "https://github.com/{{ item.user }}/{{ item.repository }}"
      dest: "/var/www/{{ item.repository }}"
  with_items:
      - { user: 'joereynolds', repository: 'boganspunkrock' }
      - { user: 'joereynolds', repository: 'util.joereynoldsaudio' }
      - { user: 'joereynolds', repository: 'joereynoldsaudio' }
      - { user: 'joereynolds', repository: 'metronome' }
      - { user: 'CISOfy', repository: 'lynis' }
  become: true

- name: Copy minio docker-compose file
  copy:
    src: ./roles/common/files/minio-docker-compose.yml
    dest: /var/www/minio/docker-compose.yml
  become: true

- name: Set Postfix option hostname
  debconf: name=postfix question="postfix/mailname" value="{{ansible_fqdn}}" vtype="string"
  become: true

- name: Set Postfix option type as internet site
  debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"
  become: true

- name: Install Postfix
  apt: package={{ item }}
  with_items:
    - postfix
    - mailutils
  become: true
