- name: Add joe user
  user:
    name: joe
    shell: /bin/bash
    groups: sudo
    append: yes
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
      - /var/www
      - /etc/apache2/sites-enabled
  become: true

- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ item }}"
  become: true
  with_items:
      - automysqlbackup
      - fail2ban
      - pwgen

- name: Clone git repos
  git:
      repo: "https://github.com/{{ item.user }}/{{ item.repository }}"
      dest: "/var/www/{{ item.repository }}"
  with_items:
      - { user: 'joereynolds', repository: 'boganspunkrock' }
      - { user: 'joereynolds', repository: 'util.joereynoldsaudio' }
      - { user: 'joereynolds', repository: 'joereynoldsaudio' }
      - { user: 'joereynolds', repository: 'metronome' }
      - { user: 'CISOfy', repository: 'lynis' }
  become: true

- name: Enable Apache rewrite module
  apache2_module:
    state: present
    name: rewrite
  become: true

- name: Copy Apache configurations
  copy:
    src: ./roles/common/files/{{ item }}
    dest: /etc/apache2/sites-enabled/{{ item }}
  with_items:
      - metronome.joereynoldsaudio.conf
      - util.joereynoldsaudio.conf
  become: true

- name: Set Postfix option hostname
  debconf: name=postfix question="postfix/mailname" value="{{ansible_fqdn}}" vtype="string"
  become: true

- name: Set Postfix option type as internet site
  debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"
  become: true

- name: Install Postfix
  apt: package={{ item }}
  with_items:
    - postfix
    - mailutils
  become: true
