- name: Add ppa:ondrej/php
  raw: "sudo add-apt-repository ppa:ondrej/php"

- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ item }}"
  become: true
  with_items:
      - fail2ban
      - composer
      - git
      - php7.1
      - php7.1-curl
      - php7.1-mbstring
      - php7.1-simplexml
